package ma.WhiteLab.service.modules.dashboard_statistiques.api;

import ma.WhiteLab.service.modules.dashboard_statistiques.dto.*;
import java.time.LocalDate;
import java.util.List;

/**
 * Service for in-depth statistical analysis and reporting.
 */
public interface StatistiquesService {

    /**
     * 1. Generates time-series data for revenue and expenses over a period.
     */
    List<TimeSeriesDTO> getRevenueVsExpenseTrend(LocalDate start, LocalDate end);

    /**
     * 2. Calculates revenue generated by each medical act category.
     */
    List<BreakdownDTO> getRevenueByActeCategory(LocalDate start, LocalDate end);

    /**
     * 3. Retrieves a list of all unpaid or partially paid invoices.
     */
    List<UnpaidInvoiceSummaryDTO> getUnpaidInvoicesReport();

    /**
     * 4. Groups patients into age brackets.
     */
    List<BreakdownDTO> getPatientAgeDistribution();

    /**
     * 5. Tracks the number of new patients registered per month.
     */
    TimeSeriesDTO getNewPatientAcquisitionTrend(LocalDate start, LocalDate end);

    /**
     * 6. Calculates the number of consultations handled by each doctor.
     */
    List<BreakdownDTO> getConsultationWorkload(LocalDate start, LocalDate end);

    /**
     * 7. Analyzes the status of all appointments.
     */
    AppointmentStatusDTO getAppointmentStatusAnalysis(LocalDate start, LocalDate end);

    /**
     * 8. Finds the most frequently prescribed medications.
     */
    List<BreakdownDTO> getTopPrescribedMedications(LocalDate start, LocalDate end, int limit);

    // ================= ADMIN STATS =================

    /**
     * Admin: Distribution of users by Role (Admin, Medecin, Secretaire).
     */
    List<BreakdownDTO> getUsersByRoleDistribution();

    /**
     * Admin: Distribution of cabinets by Category.
     */
    List<BreakdownDTO> getCabinetsByCategoryDistribution();
}
